### PR TITLE
Trove should support more object cleanup methods

### PR DESCRIPTION
**Pull request by bubshayz**
Right now, Trove only supports `Destroy` and `Disconnect` as object cleanup methods. Cleanup methods other than these 2 have to be specified through `Trove:Add`.

However, Trove *should* also support camel case versions of these cleanup methods, as developers tend to follow various style guides when writing code. However, the [Roblox Lua Style Guide](https://roblox.github.io/lua-style-guide/) generally states that methods should be generally `camelCase`.

For those who follow this (widely-used) style guide, it is inconvenient for them to specify the cleanup method through `Trove:Add`..

 This PR makes Trove support the following **additional* generic object cleanup methods:
- `destroy`
- `disconnect`

### CODE REVIEW

**Comment by Sleitnick** [comment]
Overall change looks good, thanks! Please make the changes to satisfy the lint and styling rules, then I'll merge it in.

**Comment by bubshayz** [comment]
More cleanup methods are supported (`Clean`, `Deinit`, `clean`, `deinit`)

**Comment by bubshayz** [comment]
@Sleitnick cc

**Comment by Sleitnick** [comment]
I'm not sure that Clean and Deinit should be included. It becomes a bit of a slippery slope of what should/shouldn't be added to such a list, e.g. Deconstruct, Remove, Drop, Close, etc. The `Add` method already lets you give it a custom cleanup method. I think I'm fine with adding camelCase versions of the existing ones, but not sure adding others outside of those makes much sense in the long-run.

**Comment by bubshayz** [comment]
> I'm not sure that Clean and Deinit should be included. It becomes a bit of a slippery slope of what should/shouldn't be added to such a list, e.g. Deconstruct, Remove, Drop, Close, etc. The `Add` method already lets you give it a custom cleanup method. I think I'm fine with adding camelCase versions of the existing ones, but not sure adding others outside of those makes much sense in the long-run.

Rectified.

**Comment by Sleitnick** [comment]
Pushed, Trove v1.1.0. Thanks @bubshayz!

**Pull request merged**
