### PR TITLE
structure *modules* as [name][return value] map

### PR DESCRIPTION
**Pull request by devsarim**
type Modules = { [string]: Module }

### CODE REVIEW

**Comment by Sleitnick** [comment]
This will require a major version bump, but I think it makes sense. Usually loading them and referencing by name makes the most sense.

**Review by Sleitnick — APPROVED** [review]

**Comment by Sleitnick** [comment]
Maybe I worded that wrong - my point is that we _should_ do this :)

**Comment by sarimwastaken** [comment]
Oh no you worded it fine completely fine! I'm just not too familiar with this process so I thought I had to close it once you approved it, my bad 😅

**Comment by Sleitnick** [comment]
The Loader module had a major version change & additions, which also included mapping by name instead

**Pull request closed without merging**
